apiVersion: v2
name: grafana
description: Grafana monitoring dashboard
type: application
version: 0.1.0
appVersion: "11.0.0"
dependencies:
  - name: grafana
    version: "8.11.0"
    repository: https://grafana.github.io/helm-charts
