{{- if .Values.ingress.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "task-manager.fullname" . }}-cert
spec:
  domains:
    - {{ .Values.ingress.host | quote }}
{{- end }}