apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "task-manager.fullname" . }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcp.workloadIdentityServiceAccount }}
